### ISSUE TITLE
done() is undefined when renderSync is used.

### ISSUE THREAD

**Issue by jchild3rs** [haithembelhaj/compass-importer#1]
Needs to just return the object literal if done() is undefined.

**Comment by haithembelhaj** [comment]
First of all thanks for this issue. I didn't expect any traction with this project. I looked at the problem closely and I'm not sure i can get It to work for renderSync. The main problem is that i need to trigger at least a head request to Github to check the version of the mixins. 
The misleading part was probably the "renderSync" in README file. I changed it to "render" instead.
