### ISSUE TITLE
.compass directory is missing

### ISSUE THREAD

**Issue by pishonx** [haithembelhaj/compass-importer#10]
Hi,

I am using   <a href="https://github.com/sindresorhus/grunt-sass">Grunt Sass</a>  and everytime I run my grunt task, it hangs saying "downloading compass", and no more. .

I've been  trying to dig into the issue , and I found  ".compass"  folder is missing, therefore  headers.json does not exist.  

What create this folder and how?  I have reinstalled many times using 

>  npm install --save-dev compass-importer

, I am still gettting the same message u.u 

Thanks

compass-importer": "^0.1.3"
npm v 2.14.12
Node v4.2.6

**Comment by haithembelhaj** [comment]
Sorry to hear about that. The only possible reason i can think of is maybe the npm cache.
Can you please try to delete the cache with `npm cache clean` or delete the whole `node_modules` directory.

Thanks for reporting this :)

**Comment by haithembelhaj** [comment]
By the way i just refactored the code. The importer just uses `compass-mixins` as an npm module and resolves to it's path. You could try the new version too.

**Comment by pishonx** [comment]
Hey , I cleaned the cache, uninstall completely the module and now it works ^^

Then I started a new project using the new version ,Works like a charm!  good refactoring.

Thanks for sharing

**Comment by haithembelhaj** [comment]
Glad to hear that!
