### ISSUE TITLE
Error "Functions may not be defined within control directives or other mixins" afer upgrading node-sass to 3.5.3

### ISSUE THREAD

**Issue by pshemek** [haithembelhaj/compass-importer#11]
Hello,

Afer upgrading node-sass to **3.5.3** I started getting the following error:

```
[Error running Gulp] node_modules/compass-importer/.compass/compass-mixins-master/lib/compass/functions/_lists.scss
Error: Functions may not be defined within control directives or other mixins.
        on line 81 of node_modules/compass-importer/.compass/compass-mixins-master/lib/compass/functions/_lists.scss
>>   @function compact($vars...) {
   --^
```

When using the old node-sass **3.4.1** there's no error, so I guess there's some incompatibility between these packages.

**Comment by haithembelhaj** [comment]
Hi, 

Thank you for reporting the issue. This Bug seems to be related to a compass-mixins bug https://github.com/Igosuki/compass-mixins/issues/85 . As this module solely relies on compass-mixins, I think that our best chance is to hope that it get fixed soon.
