### ISSUE TITLE
Using an old version of compass-mixins

### ISSUE THREAD

**Issue by galtalmor** [haithembelhaj/compass-importer#13]
Hi,
I wondered why you are using a private fork of compass-mixins?
And if it is actually required, I think it should be updated, they released 3 versions since your last update.
I basically was looking for the input placeholder mixin (compass/css3/user-interface) that was missing from the old version.
Thanks.

**Comment by haithembelhaj** [comment]
Hi,

Thank you for reporting this. There was a problem with an old version of compass-mixins and i had to fork the project. I included the new version and everything was working again :)

Again thank you for the support.

**Comment by galtalmor** [comment]
Awesome :+1: .
Thanks for your work.

**Comment by marklieberman** [comment]
@haithembelhaj 
I believe you forgot to update https://github.com/haithembelhaj/compass-importer/blob/master/index.js#L5 in your latest commits. I had to downgrade to 0.3.0, because I get

```
 Error: Cannot find module '@haithembelhaj/compass-mixins' from /Users/.../node_modules/compass-importer
```

on 0.3.1. Your [build status tag](https://travis-ci.org/haithembelhaj/compass-importer/jobs/146416555) seems to be failing with a similar error.

**Comment by haithembelhaj** [comment]
OHH that's why it worked :p 
I reversed to the my version of compass-mixins and will try to update it soon.

**Comment by galtalmor** [comment]
I have tried to change the dependency in both places and it seems to work just fine.
But I don't know what the original issue was, so I'm not sure.
Anyway, please try again.
Thanks.

**Comment by haithembelhaj** [comment]
If you run the tests you will see what i mean. `compass-mixins` removed the `compact` function for some reason and it breaks a lot of mixins like animation. As I said, I will try to integrate the functions that you need. 
Also feel free to contribute. I will happily add you as a contributer :)

**Comment by haithembelhaj** [comment]
Oh my god. The tests where actually wrong.
I fixed them und switched back to `compass-mixins` 

Thank you so much for the support!

**Comment by galtalmor** [comment]
:+1: 
Thanks!
