### ISSUE TITLE
if i use compass with this importer, where should i put my compass configurations?

### ISSUE THREAD

**Issue by anianj** [haithembelhaj/compass-importer#2]
Because i am using the inline-image function of compass it need to know the images_dir usually we put this configuration in config.rb

**Comment by haithembelhaj** [comment]
I don't think there is a way to support such functionality. You have to look at what is possible with the actual version of node-sass. This compass-importer imports just the mixins and functions of Compass as pure sass files so you can get the best of two worlds: node-sass performance and compass functionality. The down side is that some of the Compass functionality that is written in ruby will probably be missing.
