### ISSUE TITLE
Check online status before requesting and downloading newer compass-mixins

### ISSUE THREAD

**Issue by upstroke** [haithembelhaj/compass-importer#3]
I encountered slow render times when on a slow or non existing internet connection.
As it seems, your module is looking for newer compass mixins every time a sass compile is triggered:

index.js line: 21
request.head(githubUrl)
        .on('response', function (res) {
            if (oldHeaders.etag === res.headers.etag)
                return done({file: 'compass-mixins-master/lib/' + url});

```
        download()
    });
```

**Comment by haithembelhaj** [comment]
First of all thanks for this issue. Yeah the update logic was suboptimal. I just pushed a new version that should fix this problem.
