### ISSUE TITLE
Error when importing compass mixins

### ISSUE THREAD

**Issue by upstroke** [haithembelhaj/compass-importer#4]
I am using grunt-sass to render sass files.

When using inside scss file:
@import "compass/reset";

I get the follwoing error message:
 verify compass version ...
    >> file to import not found or unreadable: reset

**Comment by haithembelhaj** [comment]
You are totally wright. I Forgot about those. The new version should fix you problem.

**Comment by upstroke** [comment]
When looking at the linked compass mixins source that got downloaded, it seems that you do not have to make an extra @import call to parts of compass mixins you want to use like stated on the original ruby compass site (as this is what I did when following instruction on ruby compass site at: http://compass-style.org/reference/compass/reset/). Instead you just use the mixins you want right away after your compass include like so (taken from main.scss that imports all other SASS-Partials):

// import compass mixins, we use grunt compass-importer to use compass mixins with libsass
// https://github.com/haithembelhaj/compass-importer
@import "compass";

// compass mxin based on Eric Meyer's reset 2.0
@include global-reset;

So THX this been my fault, I am sorry ..
