### ISSUE TITLE
[Feature Request] specify cache directory

### ISSUE THREAD

**Issue by p2media** [haithembelhaj/compass-importer#5]
I use a temporarily directory. It would be pretty nice if I can specify the cache directory.

**Comment by haithembelhaj** [comment]
Forgot to close this one. Thanks for the idea ist Implemented :)

**Comment by haithembelhaj** [comment]
No actually not implemented sorry about that! wrong project!

The problem about this one is that it is inpossible to make it backward compatible. 

What you need is something that looks like this:

```
var compass = require('compass-importer')

sass.render({
  includePaths: [ '.compass'],
  data: '@import "compass"; .transition { @include transition(all); }',
  importer: compass(TEMPDIR)
});
```

As i wrote this I came up with an Idea 

```
var compass = require('compass-importer')

compass.cacheDirectory = '.temp';

sass.render({
  includePaths: [compass.cacheDirectory],
  data: '@import "compass"; .transition { @include transition(all); }',
  importer: compass
});
```

**Comment by haithembelhaj** [comment]
Event better the cacheDirectory is now located in `node_modules`. You can still configure it if you want with `require('compass-importer').cacheDirectory`
