### ISSUE TITLE
[BUG] Hangs while downloading compass (0.1.0)

### ISSUE THREAD

**Issue by p2media** [haithembelhaj/compass-importer#6]
I've recently updated to `compass-importer 0.1.0`.
Since then it won't  download anymore. It stops on "downloading compass ...".

It works as aspected with version `0.0.3`.

**Comment by haithembelhaj** [comment]
I just tested it again and it works. There is a somehow breaking change in 0.1.0 as you don't need to specify an `includePaths` anymore. Hope this helps
