### ISSUE TITLE
[FEATURE REQUEST] using grunt.log instead of console.log

### ISSUE THREAD

**Issue by p2media** [haithembelhaj/compass-importer#7]
It would be nice if you could use [`grunt.log`](http://gruntjs.com/api/grunt.log) instead of `console.log`.

I already forked this repository and can implement this...

**Comment by haithembelhaj** [comment]
This importer doesn't have anything todo with Grunt. `grunt-sass` is flexible enough so it's a child play to integrate it in grunt. It sure would be a nice feature for grunt users, but i don't know of a reliable method to detect the grunt runtime.
