### ISSUE TITLE
Error while importing animation module.

### ISSUE THREAD

**Issue by dmonin** [haithembelhaj/compass-importer#9]
There is an error while trying to import animation module:
`@import "compass/css3/animation";`

Results in:

```
>> file to import not found or unreadable: animation/core
>> Current dir: /[path]/node_modules/compass-importer/.compass/compass-mixins-master/lib/compass/css3/
>>   Line 2  Column 9  node_modules/compass-importer/.compass/compass-mixins-master/lib/compass/css3/_animation.scss
```

**Comment by haithembelhaj** [comment]
Are you using the lastest version of this Module? 

As you can see [here](https://github.com/haithembelhaj/compass-importer/blob/master/test/index.js#L24,L37) I wrote some tests for this particular case.

**Comment by dmonin** [comment]
hey Haithem,

thanks for prompt response! I think so, yes it must tbe, I just installed it yesterday.

packages.json:

```
"compass-importer": "*",
```

Necessary files are also contained in node_modules/../.compass cache directory, though it can't include them. Is there a CWD problem? What worked for me, is to change in compass/css3/_animation.scss to this one:
`@import "../../animation/core";`

I suppose unit tests are running in an environment where CWD is the compass-imports root directory. So SASS checks the script first relative to it's include and then in CWD (which could be different in every app). Could it be the problem?

**Comment by haithembelhaj** [comment]
This one was tricky. Forgot to publish the last version to npm
Thank you for reporting the issue.

**Comment by dmonin** [comment]
Thank you so much!
